spring:
  application:
    name: backend
  datasource:
    url: jdbc:mysql://localhost:3306/devtinderdb
    username: springstudent
    password: springstudent
  jpa:
    hibernate:
      ddl-auto: update
